server:
#  port: 8085
  port: 8088
#  ssl:
#    enabled-protocols: TLSv1.2,TLSv1.3

# 具体数据库连接配置
  data:
    redis:
      host: 127.0.0.1
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:/mapper/*.xml
  # 开启mybatis的二级缓存
  configuration:
    cache-enabled: true
# 开启sql打印
logging:
  level:
    root: INFO
    com:
      batis:
        mapper: debug
    org.springframework.web: DEBUG
# 开启数据库连接池日志

